name: Tests
on: push

jobs:
  checks:
    name: Get packages and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Getting packages
        run: flutter pub get
      - name: Running tests
        run: flutter test
 
